### ISSUE TITLE
DOCUMENTATION: Checklist for Sven

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#1017]
- [ ] Make the features list consistent in each class.

- [ ] Add the Core Classes overview.

- [ ] Explain more the Wrapper classes, and its features.

- [ ] Make a separate section of the Setup guides.

- [ ] Revise the setup guides.

- [ ] All generic class documentation should be on module level. All coding specific class documentation on the class itself.

- [ ] More examples in the documentation.

- [ ] Reference to the example missions in each class. People don't know where to look!
