### ISSUE TITLE
CARGO: Checklist to finish off the complete development

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#890]
- [x] AI_CARGO_APC, AI_CARGO_HELICOPTER, AI_CARGO_AIRPLANE All Carriers are on group level.

- [x] Check and enhance the carrier container logic (limits etc).

- [x] AI_CARGO_APC, AI_CARGO_HELICOPTER, AI_CARGO_AIRPLANE Grouped carriers can move multiple CargoSet in one load/board action.

- [x] AI_CARGO_APC Rework how to make vehicles avoid clutter on the ground when moving towards a pickup or deploy point. Make APCs follow the roads when moving to a pickup zone.

- [x] AI_CARGO_AIRPLANE should be able to start on the ground at an airbase instead of in the air (spawn logic).

- [x] Respawn of ~CARGO named groups.

- [x] Check all cargo respawning.

- [x] AI_CARGO_SHIP Check feasibility for cargo logic for ships.

- [x] Optimize the container logic in carriers. No self variables but using the carrier container cargo logic.

- [x] When carrier are destroyed, ensure that the cargo destruction is triggered and that cargo is reported as destroyed.

- [x] AI_CARGO_APC Check how to stop an APC when the waypoint has been set by a player (this is a bug in DCS, and i need to find a workaround).

- [x] Check all the cargo tasking (TAD-CGO-...) missions.

- [x] Check overall cargo logic stability (this is going to be the hard part, but we are a team to test, so ...)

- [x] Make Loaded and Unloaded event handlers for AI_CARGO_APC, AI_CARGO_HELICOPTER, AI_CARGO_AIRPLANE and maybe AI_CARGO_SHIP.

**Comment by FlightControl-User** [comment]
> AI_CARGO_APC Rework how to make vehicles avoid clutter on the ground when moving towards a pickup or deploy point. Make APCs follow the roads when moving to a pickup zone.

Implemented

**Comment by FlightControl-User** [comment]
all done. closing
